# https://github.com/awesome-containers/static-bash
ARG STATIC_BASH_VERSION=5.2.15
ARG STATIC_CURL_VERSION=7.88.1

FROM ghcr.io/awesome-containers/static-curl:$STATIC_CURL_VERSION AS static-curl

FROM ghcr.io/awesome-containers/alpine-build-essential:3.17 AS build

WORKDIR /src/curl
COPY --from=static-curl /bin/curl ./curl

RUN set -xeu; \
    strip -s -R .comment -R .gnu.version --strip-unneeded curl; \
    upx --no-progress --no-color curl; \
    upx -t --no-progress --no-color curl; \
    chmod -cR 755 curl; \
    chown -cR 0:0 curl; \
    ! ldd curl && :; \
    ./curl -V

# slim static coreutils image
FROM ghcr.io/awesome-containers/static-bash:$STATIC_BASH_VERSION-slim AS static-bash
COPY --from=static-curl /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=build /src/curl/curl /bin/curl
