name: Create Release
on:
  push:
    tags:
      - "*.**"

jobs:
  build_and_push:
    name: Build and push container image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set env
        id: env
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
          echo ::set-output name=repository::${GITHUB_REPOSITORY/-}

      - id: static-bash
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: awesome-containers/static-bash
          excludes: prerelease, draft
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to GitHub Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push container image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Containerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.env.outputs.tag }}
            ghcr.io/${{ github.repository }}:latest
            docker.io/${{ steps.env.outputs.repository }}:${{ steps.env.outputs.tag }}
            docker.io/${{ steps.env.outputs.repository }}:latest
          build-args: STATIC_BASH_VERSION=${{ steps.static-bash.outputs.release }}

      - name: Build and push slim container image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Containerfile-slim
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.env.outputs.tag }}-slim
            ghcr.io/${{ github.repository }}:latest-slim
            docker.io/${{ steps.env.outputs.repository }}:${{ steps.env.outputs.tag }}-slim
            docker.io/${{ steps.env.outputs.repository }}:latest-slim
          build-args: |
            STATIC_CURL_VERSION=${{ steps.env.outputs.tag }}
            STATIC_BASH_VERSION=${{ steps.static-bash.outputs.release }}

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ${{ github.repository }}:**${{ steps.env.outputs.tag }}**

            * `docker pull ghcr.io/${{ github.repository }}:${{ steps.env.outputs.tag }}`
            * `docker pull docker.io/${{ steps.env.outputs.repository }}:${{ steps.env.outputs.tag }}`

            ${{ github.repository }}:**${{ steps.env.outputs.tag }}-slim**

            * `docker pull ghcr.io/${{ github.repository }}:${{ steps.env.outputs.tag }}-slim`
            * `docker pull docker.io/${{ steps.env.outputs.repository }}:${{ steps.env.outputs.tag }}-slim`

          draft: false
          prerelease: false
